# Generated by Django 2.2.3 on 2019-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.IntegerField(default=0, verbose_name='Glucose level'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=0, max_length=500, verbose_name='Measurement information'),
        ),
    ]
